set(OUTPUT_DIR "${CMAKE_CURRENT_BINARY_DIR}/gre-over-ipsec-plan")
file(REMOVE_RECURSE "${OUTPUT_DIR}")
execute_process(
    COMMAND "${EVENTNET_NETNS_PLAN}" --intent intent-gre-a-b --out-dir "${OUTPUT_DIR}"
        "${SOURCE_DIR}/samples/gre-over-ipsec.yaml"
    RESULT_VARIABLE PLAN_RESULT
    OUTPUT_VARIABLE PLAN_OUTPUT
    ERROR_VARIABLE PLAN_ERROR
)
if(NOT PLAN_RESULT EQUAL 0)
    message(FATAL_ERROR "GRE plan generation failed: ${PLAN_OUTPUT}${PLAN_ERROR}")
endif()

file(READ "${OUTPUT_DIR}/vpp-route-plan.sh" VPP_PLAN)
file(READ "${OUTPUT_DIR}/vpp-netns-route-plan.sh" VPP_NETNS_PLAN)
file(READ "${OUTPUT_DIR}/gre-swanctl.conf" SWANCTL_PLAN)
file(READ "${OUTPUT_DIR}/apply-integrated.sh" INTEGRATED_PLAN)
file(READ "${OUTPUT_DIR}/rollback-selected.sh" ROLLBACK_PLAN)
if(NOT VPP_PLAN MATCHES "create gre tunnel src 203\\.0\\.113\\.10 dst 203\\.0\\.113\\.20 instance 0")
    message(FATAL_ERROR "VPP GRE create command missing")
endif()
if(NOT VPP_PLAN MATCHES "set interface ip address gre0 10\\.255\\.0\\.1/30")
    message(FATAL_ERROR "VPP GRE address command missing")
endif()
if(NOT VPP_PLAN MATCHES "ip route add 10\\.10\\.2\\.0/24 via 10\\.255\\.0\\.2 gre0")
    message(FATAL_ERROR "VPP GRE route command missing")
endif()
if(NOT VPP_NETNS_PLAN MATCHES "create gre tunnel src 203\\.0\\.113\\.10 dst 203\\.0\\.113\\.20 instance 0")
    message(FATAL_ERROR "VPP netns GRE create command missing")
endif()
if(NOT SWANCTL_PLAN MATCHES "mode = transport")
    message(FATAL_ERROR "strongSwan GRE transport mode missing")
endif()
if(NOT SWANCTL_PLAN MATCHES "local_ts = dynamic\\[gre\\]")
    message(FATAL_ERROR "strongSwan GRE local selector missing")
endif()
if(NOT SWANCTL_PLAN MATCHES "remote_ts = dynamic\\[gre\\]")
    message(FATAL_ERROR "strongSwan GRE remote selector missing")
endif()
if(NOT INTEGRATED_PLAN MATCHES "--load-conns --file out/netns-runtime/gre-swanctl.conf")
    message(FATAL_ERROR "integrated GRE strongSwan load missing")
endif()
if(NOT INTEGRATED_PLAN MATCHES "--initiate --child gre-a-b")
    message(FATAL_ERROR "integrated GRE initiation missing")
endif()
if(NOT ROLLBACK_PLAN MATCHES "--terminate --child gre-a-b")
    message(FATAL_ERROR "GRE rollback termination missing")
endif()
message(STATUS "GRE over IPsec VPP plan checks passed")
